
# MySQL 8.0 이미지를 기반으로 빌드
FROM mysql:8.0

# 환경변수 설정 (루트 비밀번호, 사용자, 데이터베이스 설정)
ENV MYSQL_ROOT_PASSWORD=sbb_password
ENV MYSQL_DATABASE=sbb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=sbb_password

# MySQL 포트 설정
EXPOSE 3306